### ISSUE TITLE
Setup blog with VuePress

### ISSUE THREAD

**Issue by edimitchel** [ElsassDev/blog#2]
This issue could be used as a whiteboad where we can persist all things we would like to do for the blog infrastructure. **Use comments for suggestions**

Framework : 
- VuePress
- Vue 3 (beta)

Code rules : 
- Use Composition API
- TypeScript

Themes :
- @recodable/vuepress-theme-tailwind-blog
  https://vuepress-theme-tailwind-blog.netlify.app/#intro
  ![image](https://user-images.githubusercontent.com/2922851/82136746-10af2080-9811-11ea-89d5-957b73c028cf.png)

Plugins :
- [vuepress-plugin-container](https://vuepress.github.io/en/plugins/container/)
- [vuepress-plugin-git-log](https://vuepress.github.io/en/plugins/git-log/)
- [vuepress-plugin-nprogress](https://vuepress.github.io/en/plugins/nprogress/)
- [vuepress-plugin-table-of-contents](https://vuepress.github.io/en/plugins/table-of-contents)
- [vuepress-plugin-typescript](https://vuepress.github.io/en/plugins/typescript/) + [vuepress-types](https://vuepress.github.io/en/tools/types/)
- [vuepress-plugin-medium-zoom](https://vuepress.github.io/en/plugins/medium-zoom/)

Other (but not the least) :
- [Code Surfer](https://codesurfer.pomb.us/)

**Comment by KeziahMoselle** [comment]
is Vue 3 relatively stable ? I don't want to refactor things for it to work in the next months

**Comment by edimitchel** [comment]
Yes, it would not evolve dramatically. No worry about that, we will don't use advanced features.

**Comment by KeziahMoselle** [comment]
Awesome, I will setup a boilerplate soon

**Comment by edimitchel** [comment]
@KeziahMoselle some news ?
